### ISSUE TITLE
I have combined the

### ISSUE THREAD

**Issue by SEUleaderYang** [hjxwhy/Block-NeRF#1]

**Comment by SEUleaderYang** [comment]
I simplify your mip-nerf code and combine it with nerf-wild to get a block module used in the paper, and aftering an eval code test it get a great effect, hope  we can cooperate to reproduce the rest of the work! Here's my email:zesongyang0@gmail.com, if that's possible

**Comment by hjxwhy** [comment]
Hello, I have emailed you!
